
INSERT INTO questions (question_text, options, correct_answer) VALUES
-- Niveau Facile
('Quel est le terme pour un logiciel malveillant qui chiffre vos fichiers et demande une rançon ?', '["Virus", "Ransomware", "Spyware", "Adware"]', 'Ransomware'),
('Quelle méthode d''attaque consiste à envoyer un email frauduleux pour voler des informations sensibles ?', '["Phishing", "Smishing", "Vishing", "Spoofing"]', 'Phishing'),
('Que signifie "2FA" dans le contexte de la sécurité des comptes ?', '["Two-Factor Authentication", "Two-Form Authorization", "Double-Factor Access", "Dual-Form Authentication"]', 'Two-Factor Authentication'),
('Quel protocole sécurise la communication entre votre navigateur et un site web (affichant un cadenas) ?', '["HTTP", "FTP", "SMTP", "HTTPS"]', 'HTTPS'),
('Comment appelle-t-on une attaque qui submerge un serveur de requêtes pour le rendre indisponible ?', '["Man-in-the-middle", "Cross-Site Scripting (XSS)", "DDoS (Distributed Denial of Service)", "SQL Injection"]', 'DDoS (Distributed Denial of Service)'),
('Quel est l''objectif principal d''un pare-feu (Firewall) ?', '["Accélérer internet", "Filtrer le trafic réseau", "Stocker des mots de passe", "Nettoyer les virus"]', 'Filtrer le trafic réseau'),
('Un mot de passe robuste doit contenir :', '["Seulement des lettres", "Le nom de votre animal", "Des majuscules, minuscules, chiffres et symboles", "Moins de 6 caractères"]', 'Des majuscules, minuscules, chiffres et symboles'),
('Qu''est-ce qu''un "cheval de Troie" (Trojan horse) en informatique ?', '["Un antivirus puissant", "Un programme qui semble légitime mais cache un code malveillant", "Un type de câble réseau", "Un bug matériel"]', 'Un programme qui semble légitime mais cache un code malveillant'),
('Pourquoi est-il important de mettre à jour régulièrement ses logiciels ?', '["Pour changer l''interface", "Pour corriger les failles de sécurité", "Pour utiliser plus de mémoire", "Pour ralentir l''ordinateur"]', 'Pour corriger les failles de sécurité'),
('Quel type de logiciel est conçu pour espionner secrètement l''activité d''un utilisateur ?', '["Spyware (Logiciel espion)", "Ransomware", "Adware", "Firewall"]', 'Spyware (Logiciel espion)'),

-- Niveau Moyen
('Qu''est-ce que l''ingénierie sociale (social engineering) ?', '["La conception de réseaux sociaux", "La manipulation psychologique pour obtenir des informations", "Le piratage de matériel informatique", "L''écriture de code sécurisé"]', 'La manipulation psychologique pour obtenir des informations'),
('Dans la triade "CIA" de la sécurité, que représente le "C" ?', '["Confidentialité", "Certificat", "Contrôle", "Cybersécurité"]', 'Confidentialité'),
('Qu''est-ce qu''une attaque "Man-in-the-Middle" (MitM) ?', '["Une attaque DDoS", "Une interception de communication entre deux parties", "Un virus dans un email", "Une faille matérielle"]', 'Une interception de communication entre deux parties'),
('Quelle est la différence principale entre un virus et un ver (worm) ?', '["Le ver peut se propager sans intervention humaine", "Le virus est moins dangereux", "Le ver ne peut pas être supprimé", "Le virus cible uniquement les emails"]', 'Le ver peut se propager sans intervention humaine'),
('Qu''est-ce qu''un VPN (Virtual Private Network) ?', '["Un antivirus", "Un réseau social pour entreprises", "Un tunnel sécurisé pour le trafic internet", "Un type de pare-feu"]', 'Un tunnel sécurisé pour le trafic internet'),
('Que signifie "smishing" ?', '["Phishing par email", "Phishing par SMS", "Phishing par appel vocal", "Phishing sur les réseaux sociaux"]', 'Phishing par SMS'),
('Qu''est-ce qu''une "faille zero-day" ?', '["Une faille qui ne dure qu''un jour", "Une faille de sécurité inconnue du développeur et non corrigée", "Une faille dans le BIOS", "Une faille qui ne nécessite aucune compétence"]', 'Une faille de sécurité inconnue du développeur et non corrigée'),
('Quel est le rôle d''un "pot de miel" (honeypot) en sécurité ?', '["Stocker des mots de passe", "Attirer et piéger les attaquants", "Chiffrer les données", "Sauvegarder des fichiers"]', 'Attirer et piéger les attaquants'),
('Qu''est-ce que le "spoofing" d''adresse IP ?', '["Cacher son adresse IP", "Changer son adresse IP", "Masquer une adresse IP en utilisant celle d''un autre", "Utiliser plusieurs adresses IP"]', 'Masquer une adresse IP en utilisant celle d''un autre'),
('Quel type de malware est souvent diffusé via des publicités en ligne infectées ?', '["Worm", "Trojan", "Adware (publiciel malveillant)", "Rootkit"]', 'Adware (publiciel malveillant)'),

-- Niveau Difficile
('Qu''est-ce qu''une injection SQL (SQLi) ?', '["Injecter du code malveillant dans une base de données via une requête", "Une mise à jour de la base de données", "Une sauvegarde de base de données", "Un type de chiffrement"]', 'Injecter du code malveillant dans une base de données via une requête'),
('Que décrit la "persistance" dans le cycle de vie d''une attaque ?', '["La capacité de l''attaquant à rester dans le système après un redémarrage", "La première phase de l''attaque", "La suppression des traces de l''attaque", "Le vol de données initial"]', 'La capacité de l''attaquant à rester dans le système après un redémarrage'),
('Qu''est-ce qu''un "rootkit" ?', '["Un kit pour débutant en piratage", "Un ensemble de logiciels malveillants donnant un accès privilégié et caché", "Un outil d''administration système", "Un type de pare-feu matériel"]', 'Un ensemble de logiciels malveillants donnant un accès privilégié et caché'),
('Dans le chiffrement asymétrique, si un message est chiffré avec une clé publique, avec quoi doit-il être déchiffré ?', '["La même clé publique", "Une clé de session", "La clé privée correspondante", "N''importe quelle clé privée"]', 'La clé privée correspondante'),
('Qu''est-ce qu''une attaque par "Cross-Site Scripting" (XSS) ?', '["Une attaque qui vole des cookies de session", "Une attaque qui injecte un script malveillant dans un site web consulté par d''autres", "Une attaque qui bloque un site web", "Une attaque contre le serveur DNS"]', 'Une attaque qui injecte un script malveillant dans un site web consulté par d''autres'),
('Que signifie "CVE" dans le monde de la cybersécurité ?', '["Common Vulnerabilities and Exposures", "Critical Vulnerability Entry", "Cybernetic Violation Event", "Common Virus Encyclopedia"]', 'Common Vulnerabilities and Exposures'),
('Quel est l''objectif d''une analyse statique de code de sécurité (SAST) ?', '["Tester l''application en cours d''exécution", "Trouver des failles dans le code source sans l''exécuter", "Simuler une attaque de phishing", "Analyser le trafic réseau"]', 'Trouver des failles dans le code source sans l''exécuter'),
('Qu''est-ce qu''un "APT" (Advanced Persistent Threat) ?', '["Un antivirus avancé", "Une attaque sophistiquée et ciblée menée sur une longue période", "Un protocole de transfert de fichiers", "Un type de rapport de sécurité"]', 'Une attaque sophistiquée et ciblée menée sur une longue période'),
('Quelle est la fonction du "salage" (salting) de mot de passe ?', '["Rendre le mot de passe plus long", "Ajouter une donnée aléatoire unique à chaque mot de passe avant de le hacher", "Chiffrer le mot de passe", "Supprimer les caractères spéciaux"]', 'Ajouter une donnée aléatoire unique à chaque mot de passe avant de le hacher'),
('Qu''est-ce qu''une attaque "DNS tunneling" ?', '["Une attaque qui modifie les enregistrements DNS", "Utiliser le protocole DNS pour exfiltrer des données ou créer un canal de commande", "Une attaque qui cible les serveurs DNS racine", "Une méthode pour accélérer les requêtes DNS"]', 'Utiliser le protocole DNS pour exfiltrer des données ou créer un canal de commande'),

-- Thèmes variés
('Lequel de ces éléments n''est PAS un facteur d''authentification ?', '["Quelque chose que vous savez (mot de passe)", "Quelque chose que vous êtes (biométrie)", "Quelque chose que vous possédez (téléphone)", "Quelque chose que vous voyez (image)"]', 'Quelque chose que vous voyez (image)'),
('Qu''est-ce que l''"obfuscation" de code ?', '["Rendre le code plus lisible", "Rendre le code difficile à comprendre pour un humain", "Commenter le code", "Optimiser le code pour la vitesse"]', 'Rendre le code difficile à comprendre pour un humain'),
('Quel port est généralement utilisé par le protocole SSH (Secure Shell) ?', '["80", "443", "22", "21"]', '22'),
('Qu''est-ce qu''un "keylogger" ?', '["Un gestionnaire de mots de passe", "Un logiciel qui enregistre les frappes au clavier", "Un outil de chiffrement de disque", "Un type de serrure physique"]', 'Un logiciel qui enregistre les frappes au clavier'),
('Dans la triade "CIA", que représente le "I" ?', '["Intégrité", "Information", "Internet", "Infrastructure"]', 'Intégrité'),
('Quel type de test de sécurité implique d''avoir une connaissance complète du système cible ?', '["Test en boîte noire (Black Box)", "Test en boîte grise (Gray Box)", "Test en boîte blanche (White Box)", "Test de vulnérabilité"]', 'Test en boîte blanche (White Box)'),
('Qu''est-ce qu''un "botnet" ?', '["Un réseau social pour robots", "Un réseau d''ordinateurs infectés contrôlés à distance", "Un type de pare-feu", "Une convention de hackers"]', 'Un réseau d''ordinateurs infectés contrôlés à distance'),
('Quelle organisation est connue pour publier le "Top 10 des risques de sécurité des applications web" ?', '["Microsoft", "Google", "OWASP", "SANS Institute"]', 'OWASP'),
('Qu''est-ce que le "credential stuffing" ?', '["Remplir un formulaire avec de fausses informations", "Utiliser des listes de mots de passe volés pour se connecter à de multiples services", "Stocker des mots de passe en toute sécurité", "Partager des mots de passe avec des collègues"]', 'Utiliser des listes de mots de passe volés pour se connecter à de multiples services'),
('Quel est le but de la stéganographie ?', '["Chiffrer un message", "Compresser un message", "Cacher un message à l''intérieur d''un autre fichier (comme une image)", "Signer numériquement un message"]', 'Cacher un message à l''intérieur d''un autre fichier (comme une image)'),

-- Questions supplémentaires
('Lequel de ces hachages est considéré comme obsolète et non sécurisé pour les mots de passe ?', '["SHA-256", "bcrypt", "MD5", "Argon2"]', 'MD5'),
('Qu''est-ce qu''une "sandbox" (bac à sable) en sécurité informatique ?', '["Un jeu pour apprendre la sécurité", "Un environnement isolé pour exécuter des programmes non fiables", "Un type de base de données", "Un forum pour hackers"]', 'Un environnement isolé pour exécuter des programmes non fiables'),
('Que signifie "BYOD" (Bring Your Own Device) ?', '["Une politique autorisant les employés à utiliser leurs appareils personnels au travail", "Une marque d''ordinateurs", "Un protocole de sécurité réseau", "Un type de logiciel malveillant"]', 'Une politique autorisant les employés à utiliser leurs appareils personnels au travail'),
('Quel type d''attaque exploite les failles dans la gestion des sessions d''un site web ?', '["Session Hijacking (Détournement de session)", "DDoS", "Phishing", "SQL Injection"]', 'Session Hijacking (Détournement de session)'),
('Qu''est-ce qu''un "CERT" ou "CSIRT" ?', '["Un certificat de sécurité", "Une équipe d''intervention en cas d''incident de sécurité informatique", "Un logiciel d''audit", "Une norme de sécurité"]', 'Une équipe d''intervention en cas d''incident de sécurité informatique'),
('Quel est le rôle principal du protocole TLS ?', '["Gérer les adresses IP", "Chiffrer les données en transit sur un réseau", "Stocker des fichiers", "Router les paquets de données"]', 'Chiffrer les données en transit sur un réseau'),
('Qu''est-ce qu''une attaque par force brute ?', '["Une attaque très rapide", "Essayer toutes les combinaisons possibles de mots de passe", "Une attaque qui détruit les données", "Une attaque physique contre un serveur"]', 'Essayer toutes les combinaisons possibles de mots de passe'),
('Dans la triade "CIA", que représente le "A" ?', '["Authentification", "Disponibilité (Availability)", "Accès", "Audit"]', 'Disponibilité (Availability)'),
('Qu''est-ce qu''un "logiciel rançongiciel" est une autre appellation pour ?', '["Spyware", "Adware", "Ransomware", "Virus"]', 'Ransomware');
